"use client";
import Link from "next/link";
import { Pagination,emptyPage,type PageInfo } from "@/components/pagination";
import { CreatorImport } from "@/components/creator-import";
import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
type Creator={id:string;name:string;source_url:string;daily:boolean;status:string;error_summary:string|null;last_checked_at:string|null;next_check_at:string;last_new_count:number};
const time=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN'):'尚未完成';
export function CreatorMonitor(){
 const [loaded,setLoaded]=useState(false);
 const [items,setItems]=useState<Creator[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[epoch,setEpoch]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function load(){try{const r=await fetch('/api/creators',{cache:'no-store',signal:controller.signal});const d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error(d.message||'无法读取创作者');if(!controller.signal.aborted){setItems(d);setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败')}finally{if(!controller.signal.aborted){setLoaded(true);timer=setTimeout(load,5000)}}}
  void load();return()=>{controller.abort();clearTimeout(timer)};
 },[epoch]);
 async function action(path:string,method:string,body?:unknown){setBusy(true);setMessage('');try{
  const r=await fetch('/api/creators'+path,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.message||'操作失败');setMessage(d.message||'监控设置已保存。');setEpoch(v=>v+1);
 }catch(e){setMessage(e instanceof Error?e.message:'请求失败')}finally{setBusy(false)}}
 return <><section className="panel"><div className="section-heading"><div><h2>添加对标创作者</h2><p>收录近期作品，按需研究；自动检查由你选择开启。</p></div></div><CreatorImport onCreated={()=>setEpoch(v=>v+1)}/></section><section className="panel creator-list"><h2>关注的创作者{loaded&&!error?` · ${items.length}`:""}</h2>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}{!loaded?<p role="status">正在读取创作者…</p>:!items.length?<p>{error?'列表读取失败，正在重试。':'尚未添加创作者。'}</p>:items.map(item=><article className="creator-card" key={item.id}><h3><Link href={`/creators/${item.id}`}>{item.name}</Link></h3><p>{item.status==='BLOCKED'?'接口需处理，自动检查已阻断':item.status==='PROCESSING'?'正在检查更新':item.status==='FAILED'?'检查失败':item.status==='COMPLETED'?'检查完成':'等待首次检查'} · 上次新增收录 {item.last_new_count} 条</p><p>上次完成：{time(item.last_checked_at)} · {item.status==='BLOCKED'?'接口恢复后请手动检查':item.daily?'下次检查：'+time(item.next_check_at):'自动检查已暂停'}</p>{item.error_summary&&<p className="task-error">{item.error_summary}</p>}<div className="editor-actions"><Link href={`/feed?creator=${item.id}`}>查看已收录作品</Link><a href={item.source_url} target="_blank" rel="noreferrer">打开抖音主页</a><Button variant="outline" disabled={busy||item.status==='PROCESSING'} onClick={()=>void action('/'+item.id+'/check','POST')}>检查更新</Button><Button variant="outline" disabled={busy} onClick={()=>void action('/'+item.id,'PATCH',{daily:!item.daily})}>{item.daily?'暂停每日检查':'开启每日检查'}</Button></div></article>)}</section></>;
}
type FeedItem={id:string;title:string;creator_id:string;creator_name:string;platform:string;analysis_status:string;discovered_at:string;published_at:string|null};
function FeedContent({creatorId}:{creatorId?:string}){
 const [page,setPage]=useState(1),[pageInfo,setPageInfo]=useState<PageInfo>(emptyPage),[availableCreators,setAvailableCreators]=useState<[string,string][]>([]);
 const search=useSearchParams();
 const [items,setItems]=useState<FeedItem[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[creator,setCreator]=useState(search.get('creator')||'all'),[status,setStatus]=useState('all'),[sort,setSort]=useState('published'),[period,setPeriod]=useState('all');
 useEffect(()=>{setCreator(search.get('creator')||'all')},[search]);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;setLoading(true);
  async function load(){try{const params=new URLSearchParams({page:String(page),q,status,sort,days:period==='all'?'0':period});if(creatorId||creator!=='all')params.set('creator_id',creatorId||creator);const r=await fetch('/api/feed?'+params,{cache:'no-store',signal:controller.signal});const response=await r.json();const d=Array.isArray(response)?response:response.items;if(!r.ok||!Array.isArray(d))throw new Error(response.message||'读取失败');if(!controller.signal.aborted){setItems(d);setPageInfo(Array.isArray(response)?{...emptyPage,total:d.length}:response);setAvailableCreators(response.creators?response.creators.map((c:{id:string;name:string})=>[c.id,c.name]):Array.from(new Map(d.map((item:FeedItem)=>[item.creator_id,item.creator_name])).entries()) as [string,string][]);setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败')}finally{if(!controller.signal.aborted){setLoading(false);timer=setTimeout(load,15000)}}}
  void load();return()=>{controller.abort();clearTimeout(timer)};
 },[creatorId,page,q,creator,status,period,sort]);
 const creators=availableCreators;
 const shown=items.filter(item=>(creatorId||creator==='all'||item.creator_id===creator)&&(status==='all'||item.analysis_status===status)&&[item.title,item.creator_name].join(' ').toLowerCase().includes(q.trim().toLowerCase())&&(period==='all'||!!item.published_at&&Date.parse(item.published_at)>=Date.now()-Number(period)*86400000)).sort((a,b)=>{const key=sort==='published'?'published_at':'discovered_at';return (Date.parse(b[key]||'')||0)-(Date.parse(a[key]||'')||0)||a.id.localeCompare(b.id)});
 const statusNames:Record<string,string>={NOT_STARTED:'待分析',PENDING:'等待分析',PROCESSING:'分析中',COMPLETED:'已分析',FAILED:'分析失败'};
 return <section className="panel discovery-panel"><div className="section-heading"><div><h2>主动探索内容</h2><p>分页浏览已收录作品，自行筛选研究对象。今日情报负责精选，作品库负责收藏和整理。</p></div><Link className="text-link" href="/creators">管理创作者</Link></div><div className="library-filters"><label>关键词<input aria-label="情报关键词" value={q} onChange={e=>{setPage(1);setQ(e.target.value)}} placeholder="标题或创作者"/></label>{!creatorId&&<label>创作者<select aria-label="情报创作者" value={creator} onChange={e=>{setPage(1);setCreator(e.target.value)}}><option value="all">全部创作者</option>{creators.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}<label>分析状态<select aria-label="情报分析状态" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="all">全部状态</option><option value="NOT_STARTED">待分析</option><option value="COMPLETED">已分析</option><option value="PROCESSING">分析中</option><option value="FAILED">分析失败</option></select></label><label>发布时间<select aria-label="情报发布时间" value={period} onChange={e=>{setPage(1);setPeriod(e.target.value)}}><option value="all">不限时间</option><option value="1">最近 24 小时发布</option><option value="7">最近 7 天发布</option><option value="30">最近 30 天发布</option></select></label><label>排序<select aria-label="情报排序" value={sort} onChange={e=>{setPage(1);setSort(e.target.value)}}><option value="published">最新发布优先</option><option value="collected">最新收录优先</option></select></label></div>{error?<div className="audit-empty" role="alert"><h3>暂时无法读取情报</h3><p>{error}</p></div>:loading?<p className="audit-empty" role="status">正在读取情报…</p>:<><p className="result-count">本页 {shown.length} 条 · 共 {pageInfo.total} 条 · 发布与收录时间分别展示</p>{!shown.length?<div className="audit-empty"><h3>没有符合条件的内容</h3><p>尝试调整关键词、发布时间或分析状态。</p><Button variant="outline" onClick={()=>{setPage(1);setQ('');setCreator('all');setPeriod('all');setStatus('all')}}>清除筛选</Button></div>:<div className="discovery-list">{shown.map(item=><article className="discovery-row" key={item.creator_id+item.id}><div><span className="brief-meta">{item.creator_name}</span><h3><Link href={`/works/${item.id}`}>{item.title}</Link></h3><p className="brief-meta">发布：{item.published_at?time(item.published_at):'未知'} · 收录：{time(item.discovered_at)}</p></div><span className="neutral-label">{statusNames[item.analysis_status]||item.analysis_status}</span><Link className="text-link" href={`/works/${item.id}?tab=analysis`}>{item.analysis_status==='COMPLETED'?'阅读拆解':'查看并研究'}</Link></article>)}</div>}</>}<Pagination info={pageInfo} busy={loading} onPage={setPage}/></section>;
}
export function CreatorFeed({creatorId}:{creatorId?:string}){return <Suspense fallback={<p>正在读取情报…</p>}><FeedContent creatorId={creatorId}/></Suspense>}
