"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
type Project={id:string;title:string;idea:string|null;output_language:string;status:string;updated_at:string};
const languages:Record<string,string>={'zh-CN':'中文',en:'English','zh-en':'中英双语'};
export function CreationSpace(){
 const router=useRouter(),[items,setItems]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[epoch,setEpoch]=useState(0),[scope,setScope]=useState('active'),[q,setQ]=useState(''),[language,setLanguage]=useState('all'),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[idea,setIdea]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/creation-projects',{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error(d.message||'项目列表格式异常');if(!controller.signal.aborted){setItems(d);if(!d.length)setOpen(true)}}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[epoch]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/creation-projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.trim(),idea:idea.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.message||'创建失败');router.push('/creation/'+encodeURIComponent(d.id))}catch(e){setMessage(e instanceof Error?e.message:'创建失败');setBusy(false)}}
 const shown=items.filter(item=>(scope==='all'||scope==='active'&&item.status!=='ARCHIVED'||scope===item.status)&&(language==='all'||item.output_language===language)&&(item.title+' '+(item.idea||'')).toLowerCase().includes(q.trim().toLowerCase()));
 return <><section className="panel"><div className="section-heading"><div><h2>继续你的创作</h2><p>最近编辑的项目优先。作品库保存外部参考，这里保存你自己的草稿。</p></div><Button variant="outline" onClick={()=>setOpen(true)}>新建创作</Button></div><div className="library-filters"><label>项目状态<select aria-label="筛选项目状态" value={scope} onChange={e=>setScope(e.target.value)}><option value="active">未归档</option><option value="DRAFT">草稿</option><option value="COMPLETED">已完成</option><option value="ARCHIVED">已归档</option><option value="all">全部</option></select></label><label>搜索项目<input aria-label="搜索创作" value={q} onChange={e=>setQ(e.target.value)} placeholder="标题或创作想法"/></label><label>输出语言<select aria-label="筛选创作语言" value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">全部语言</option>{Object.entries(languages).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>{loading?<p className="audit-empty" role="status">正在读取创作项目…</p>:error?<div className="audit-empty" role="alert"><h3>暂时无法读取创作</h3><p>{error}</p><Button variant="outline" onClick={()=>setEpoch(v=>v+1)}>重新读取</Button></div>:shown.length?<div className="data-list">{shown.map(item=><article className="data-row" key={item.id}><div><Link className="work-title-link" href={'/creation/'+item.id}>{item.title}</Link><span className="project-idea">{item.idea||'尚未记录创作想法'}</span></div><span>{languages[item.output_language]||item.output_language}<br/>{item.status==="ARCHIVED"?"已归档":item.status==="COMPLETED"?"已完成":"草稿"}</span><span>上次编辑<br/>{new Date(item.updated_at).toLocaleString('zh-CN')}</span><Link className="text-link" href={'/creation/'+item.id}>{item.status==="ARCHIVED"?"查看 / 恢复":"继续创作"}</Link></article>)}</div>:<p className="audit-empty">{items.length?'没有符合筛选条件的项目。':'还没有自己的创作，可以先记录一个想法。'}</p>}</section><details className="panel new-project" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>新建创作项目</summary><form className="creation-form" onSubmit={create}><label>项目标题<input aria-label="项目标题" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>创作想法<textarea aria-label="创作想法" maxLength={10000} value={idea} onChange={e=>setIdea(e.target.value)} placeholder="主题、受众或核心观点（可稍后完善）"/></label><Button type="submit" disabled={busy||!title.trim()}>{busy?'创建中…':'创建并开始编辑'}</Button>{message&&<p role="alert">{message}</p>}</form></details></>;
}
