"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Sparkles, ArrowRight, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CreateFromWork } from "@/components/create-from-work";
type Candidate={id:string;title:string;author:string|null;published_at:string|null};
type Brief={candidate_count:number;ready_count:number;pending_count:number;picks:(Candidate&{summary:string;reasons:string[];score:number;evidence:{quote:string;claim:string}[]})[];pending:(Candidate&{reason:string;href:string})[]};
export function DailyBrief(){
 const [data,setData]=useState<Brief|null>(null),[error,setError]=useState(''),[epoch,setEpoch]=useState(0);
 useEffect(()=>{const controller=new AbortController();setError('');fetch('/api/today',{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||'读取失败');if(!controller.signal.aborted)setData(d)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[epoch]);
 return <><section className="brief-intro"><div><p className="eyebrow">DAILY RESEARCH BRIEF</p><h2>今天，先研究值得创作的内容</h2><p>从近 7 天收录的资料中，选出有完整分析与原文证据的最多 5 条。按已有 AI 参考评分排序；精选不代表今天发布或平台热度排名。</p></div><Button variant="outline" onClick={()=>setEpoch(v=>v+1)}>刷新简报</Button></section>{error?<section className="panel audit-empty" role="alert"><h3>简报暂时不可用</h3><p>{error}</p></section>:!data?<p role="status">正在整理已有分析…</p>:<><div className="brief-counts"><span>近 7 天收录 <strong>{data.candidate_count}</strong></span><span>具备推荐依据 <strong>{data.ready_count}</strong></span><span>待分析或核验 <strong>{data.pending_count}</strong></span></div><div className="daily-layout"><section><div className="section-heading"><h2><Sparkles size={19}/>今日研究精选</h2><Link href="/feed">探索更多<ArrowRight size={15}/></Link></div>{data.picks.length?<div className="brief-picks">{data.picks.map((item,index)=><article className="panel brief-pick" key={item.id}><span className="brief-rank">精选 {index+1} · AI 参考分 {item.score}</span><h3><Link href={`/works/${item.id}?tab=analysis`}>{item.title}</Link></h3><p className="brief-meta">{item.author||'作者未标记'} · 发布于 {item.published_at?new Date(item.published_at).toLocaleDateString('zh-CN'):'未知日期'}</p><p>{item.summary}</p><h4>为什么值得研究</h4><ul>{item.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul>{item.evidence[0]&&<blockquote>“{item.evidence[0].quote}”</blockquote>}<Link className="text-link" href={`/works/${item.id}?tab=analysis`}>阅读完整拆解<ArrowRight size={14}/></Link><CreateFromWork workId={item.id} title={item.title}/></article>)}</div>:<div className="panel audit-empty"><BookOpen size={28}/><h3>还没有具备推荐依据的内容</h3><p>先完成逐字稿、分析和引用核验。素材不足时不凑足精选，不会自动调用付费接口。</p><Link className="text-link" href="/feed">选择一条素材开始研究<ArrowRight size={15}/></Link></div>}</section><aside className="panel brief-sidebar"><h2>下一步研究</h2><p>以下是待处理素材，不是 AI 推荐。</p>{data.pending.length?data.pending.map(item=><article key={item.id}><span>{item.reason}</span><h3><Link href={item.href}>{item.title}</Link></h3><Link className="text-link" href={item.href}>继续研究<ArrowRight size={14}/></Link></article>):<p>暂无待处理素材。</p>}<Link className="text-link" href="/creation">回到自己的创作<ArrowRight size={14}/></Link></aside></div></>}</>;
}
