"use client";
import { useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
type Preferences={default_output_language:string;default_platform:string;revision:number};
export function LocalSettings(){
 const [values,setValues]=useState<Preferences|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/settings',{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);if(!controller.signal.aborted)setValues(d)}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message)});return()=>controller.abort()},[]);
 async function save(){if(!values)return;setBusy(true);setMessage('');try{const r=await fetch('/api/settings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...values,expected_revision:values.revision})});const d=await r.json();if(!r.ok)throw new Error(d.message);setValues(d);setMessage('默认偏好已保存，仅用于以后新建的创作项目。')}catch(e){setMessage(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}
 return <section className="panel"><div className="section-heading"><div><h2>本地创作偏好</h2><p>默认值用于新项目，已有项目继续使用自己的配置。原文保留源语言，内容分析目前输出中文。</p></div></div>{values?<div className="library-filters"><label>默认创作语言<select aria-label="默认创作语言" value={values.default_output_language} onChange={e=>setValues({...values,default_output_language:e.target.value})}><option value="zh-CN">中文</option><option value="en">English</option><option value="zh-en">中英双语</option></select></label><label>默认目标平台<select aria-label="默认目标平台" value={values.default_platform} onChange={e=>setValues({...values,default_platform:e.target.value})}>{[['tiktok','TikTok'],['instagram','Instagram'],['x','X / Twitter'],['douyin','抖音'],['xiaohongshu','小红书']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><Button variant="outline" disabled={busy} onClick={()=>void save()}>保存默认偏好</Button></div>:!message&&<p className="audit-empty">正在读取偏好…</p>}{message&&<p className="quiet-note" role="status">{message}</p>}</section>;
}
