"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { ExportDraft } from "@/components/export-draft";
type Result={translation?:string;summary?:string;hook?:string;structure?:string[];key_points?:string[];content_score?:number;score_reasons?:string[];evidence?:{claim:string;quote:string}[]};
type Run={id:string;kind:string;language:string;status:string;result:Result|null;source_text:string;source_stale:boolean;legacy:boolean;evidence_verified:boolean;completed_units:number;total_units:number;error_summary:string|null;created_at:string};
type Research={source_ready:boolean;source_language:string|null;history:Run[]};
export function ResearchPanel({workId,kind}:{workId:string;kind:'translation'|'analysis'}){
 const search=useSearchParams();
 const [language,setLanguage]=useState(search.get('language')==='en'?'en':'zh-CN'),[data,setData]=useState<Research|null>(null),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[epoch,setEpoch]=useState(0),[loading,setLoading]=useState(true);
 const target=search.get('language')===language?search.get('research'):null;
 useEffect(()=>{setSelected('');setData(null)},[workId,kind,language]);
 useEffect(()=>{
  const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;setLoading(true);setError('');
  async function load(){try{
   const query=new URLSearchParams({kind,language});if(target)query.set('run_id',target);
   const r=await fetch(`/api/works/${encodeURIComponent(workId)}/research?${query}`,{cache:'no-store',signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.message||'读取失败');
   if(!controller.signal.aborted){setData(d);setError('');setSelected(current=>d.history.some((run:Run)=>run.id===current)?current:d.history.some((run:Run)=>run.id===target)?target:d.history[0]?.id||'');if(d.history.some((run:Run)=>['PENDING','PROCESSING'].includes(run.status)))timer=setTimeout(load,2500)}
  }catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'读取失败');timer=setTimeout(load,5000)}}finally{if(!controller.signal.aborted)setLoading(false)}}
  void load();return()=>{controller.abort();clearTimeout(timer)};
 },[workId,kind,language,epoch,target]);
 async function start(){setBusy(true);setError('');try{const r=await fetch(`/api/works/${encodeURIComponent(workId)}/research`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,language})});const d=await r.json();if(!r.ok)throw new Error(d.message);setSelected(d.run_id);setEpoch(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'无法开始')}finally{setBusy(false)}}
 const run=data?.history.find(item=>item.id===selected),result=run?.result,running=data?.history.some(item=>['PENDING','PROCESSING'].includes(item.status));
 return <><section className="panel research-toolbar"><h2>{kind==='translation'?'译稿与原文对照':'内容分析'}</h2><p>{kind==='translation'?'译稿用于理解内容，不替换原文。较长材料分段翻译，时间轴仍以原文为准。':'选择报告语言；证据引文保留原语言，必须能在此次原文中逐字找到。'}</p><div className="library-filters"><label>{kind==='translation'?'译稿语言':'分析语言'}<select aria-label="研究语言" value={language} disabled={busy||!!running} onChange={e=>setLanguage(e.target.value)}><option value="zh-CN">中文</option><option value="en">English</option></select></label><Button disabled={busy||!!running||!data?.source_ready} onClick={()=>void start()}>{busy?'正在提交…':running?'任务处理中…':kind==='translation'?'生成译稿':'生成此语言分析'}</Button></div>{!loading&&data&&!data.source_ready&&<p>请先<Link className="text-link" href={`/works/${workId}?tab=transcript`}>完成原文逐字稿</Link>。</p>}<p className="quiet-note">生成会调用已配置的 GPT 模型；仅切换语言、查看历史或导出不会发起生成。</p>{error&&<p role="alert">{error}</p>}</section>{loading&&!data?<p role="status">正在读取研究记录…</p>:data&&<section className="panel research-results">{data.history.length?<><label>此语言最近 20 次记录<select aria-label="研究记录" value={selected} onChange={e=>setSelected(e.target.value)}>{data.history.map(item=><option key={item.id} value={item.id}>{new Date(item.created_at).toLocaleString('zh-CN')} · {item.status==='COMPLETED'?'完成':item.status==='FAILED'?'失败':'处理中'}</option>)}</select></label>{run?.source_stale&&<p role="alert">当前原文与这次结果使用的原文不同，建议重新生成。</p>}{run?.legacy&&<p>这是原有报告；历史原文快照时间未记录，请对照当前原文核验。</p>}{run&&['PENDING','PROCESSING'].includes(run.status)&&<p role="status">{run.status==='PENDING'?'等待处理':'模型处理中'} · 已完成 {run.completed_units} / {run.total_units} 个片段</p>}{run?.error_summary&&<p role="alert">{run.error_summary} 可以重新生成，或选择之前的完成记录。</p>}{run?.status==='COMPLETED'&&result&&(kind==='translation'?<><div className="translation-columns"><section><h3>本次使用的原文</h3><p>{run.source_text}</p></section><section><h3>{language==='en'?'English 译稿':'中文译稿'}</h3><p>{result.translation}</p></section></div><ExportDraft title={'译稿-'+workId} body={result.translation||''} workId={workId}/></>:<article className="analysis-report"><div className="research-score">AI 参考分 <strong>{result.content_score??'—'}</strong><span>不代表真实流量或事实真实性</span></div><section><h3>内容摘要</h3><p>{result.summary}</p></section><section><h3>开场 Hook</h3><p>{result.hook}</p></section><section><h3>内容结构</h3><ol>{result.structure?.map((text,i)=><li key={i}>{text}</li>)}</ol></section><section><h3>关键要点</h3><ul>{result.key_points?.map((text,i)=><li key={i}>{text}</li>)}</ul></section><section><h3>评分理由</h3><ul>{result.score_reasons?.map((text,i)=><li key={i}>{text}</li>)}</ul></section><section><h3>原文证据</h3><p>{run.evidence_verified?'引用已通过逐字匹配，观点是否成立仍需判断。':'引用尚未通过核验，请对照原文检查。'}</p>{result.evidence?.map((item,i)=><blockquote key={i}><p>{item.claim}</p><cite>“{item.quote}”</cite></blockquote>)}</section></article>)}</>:<div className="audit-empty"><h3>此语言还没有{kind==='translation'?'译稿':'分析报告'}</h3><p>选择语言后主动生成；已有其他语言的记录保持不变。</p></div>}</section>}</>;
}
