"use client";
import Link from "next/link";
import { Pagination,emptyPage,type PageInfo } from "@/components/pagination";
import { useEffect, useState } from "react";
import { WorkOrganization, emptyPreferences, type WorkPreferences } from "@/components/work-organization";
type Work={transcript_status?:string;analysis_status?:string;id:string;title:string|null;platform:string;external_id:string;status:string;metadata:{author_name:string|null}|null;preferences:WorkPreferences};
const platforms:Record<string,string>={douyin:'抖音',tiktok:'TikTok',youtube:'YouTube'};
export function WorkLibrary(){
 const [page,setPage]=useState(1),[pageInfo,setPageInfo]=useState<PageInfo>(emptyPage),[allTags,setAllTags]=useState<string[]>([]);
 const [items,setItems]=useState<Work[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[platform,setPlatform]=useState('all'),[scope,setScope]=useState('active'),[tag,setTag]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);async function load(){try{const r=await fetch('/api/works?'+new URLSearchParams({page:String(page),q,platform,scope,tag}),{cache:'no-store',signal:controller.signal});const response=await r.json();const data=Array.isArray(response)?response:response.items;if(!r.ok||!Array.isArray(data))throw new Error(response.message||'读取失败');if(!controller.signal.aborted){setPageInfo(Array.isArray(response)?{...emptyPage,total:data.length}:response);setAllTags(response.tags||data.flatMap((item:Work)=>item.preferences?.tags||[]));setItems(data.map(item=>({...item,preferences:item.preferences||emptyPreferences})));setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败')}finally{if(!controller.signal.aborted)setLoading(false)}}void load();window.addEventListener('creator-radar:refresh',load);return()=>{controller.abort();window.removeEventListener('creator-radar:refresh',load)}},[page,q,platform,scope,tag]);
 const tags=Array.from(new Set(allTags)).sort();
 const shown=items.filter(item=>(platform==='all'||item.platform===platform)&&(scope==='all'||scope==='active'&&!item.preferences.archived||scope==='favorites'&&item.preferences.favorite&&!item.preferences.archived||scope==='archived'&&item.preferences.archived)&&(!tag||item.preferences.tags.includes(tag))&&[item.title,item.external_id,item.metadata?.author_name,...item.preferences.tags].join(' ').toLowerCase().includes(q.trim().toLowerCase()));
 return <section className="panel"><div className="section-heading"><div><h2>作品库 · {pageInfo.total}</h2><p>搜索标题、作者、作品 ID 或标签。归档只隐藏作品，不删除逐字稿、分析或关联草稿。</p></div></div><div className="library-filters"><label>搜索<input aria-label="搜索作品" value={q} onChange={e=>{setPage(1);setQ(e.target.value)}} placeholder="标题、作者或标签"/></label><label>平台<select aria-label="作品平台" value={platform} onChange={e=>{setPage(1);setPlatform(e.target.value)}}><option value="all">全部平台</option>{Object.entries(platforms).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>范围<select aria-label="作品范围" value={scope} onChange={e=>{setPage(1);setScope(e.target.value)}}><option value="active">未归档</option><option value="favorites">收藏</option><option value="archived">已归档</option><option value="all">全部</option></select></label><label>标签<select aria-label="筛选标签" value={tag} onChange={e=>{setPage(1);setTag(e.target.value)}}><option value="">全部标签</option>{tags.map(t=><option key={t} value={t}>{t}</option>)}</select></label></div>{error?<p role="alert">{error}</p>:loading?<p>正在读取作品…</p>:!shown.length?<p className="quiet-note">没有符合条件的作品，请调整筛选或通过右上角添加作品。</p>:<div className="data-list">{shown.map(item=><article className="data-row" key={item.id}><div><Link className="work-title-link" href={`/works/${item.id}`}>{item.title||item.external_id}</Link><span>{item.analysis_status==="COMPLETED"?"已生成分析":item.analysis_status==="PROCESSING"?"分析中":item.transcript_status==="COMPLETED"?"逐字稿就绪 · 待分析":item.transcript_status==="PROCESSING"?"转写中":item.analysis_status==="FAILED"||item.transcript_status==="FAILED"?"处理失败 · 查看详情":item.status==="READY"?"元数据就绪 · 待转写":item.status==="FAILED"?"采集失败":"待采集"}</span><span>{item.preferences.tags.join(' · ')||'暂无标签'}</span></div><span>{platforms[item.platform]||item.platform}</span><span>{item.metadata?.author_name||'作者未知'}</span><WorkOrganization workId={item.id} initial={item.preferences} onSaved={preferences=>{setItems(current=>current.map(w=>w.id===item.id?{...w,preferences}:w));window.dispatchEvent(new Event("creator-radar:refresh"));}}/></article>)}</div>}<Pagination info={pageInfo} busy={loading} onPage={setPage}/></section>;
}
