"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, BarChart3, CalendarDays, Clock3, FileText, LoaderCircle, ShieldCheck, UserRound } from "lucide-react";

type Detail={id:string;platform:"douyin"|"tiktok"|"youtube";external_id:string;source_url:string;title:string|null;status:string;metadata:null|{provider:string;author_id:string|null;author_name:string|null;cover_url:string|null;duration_seconds:number|null;published_at:string|null;metrics:Record<string,string|number>|null;fetched_at:string};latest_task:null|{stage:string;status:string;error_summary:string|null}};
type TranscriptState={availability:"READY"|"PENDING"|"FAILED"|"PLATFORM_CAPTIONS"|"ASR_AVAILABLE"|"ASR_REQUIRED";message?:string;action:string|null;transcript:null|{status:string;language:string|null;provider:string|null;text:string|null;segments:Array<{start:number;end:number;text:string}>|null;error_summary:string|null}};
const platforms={douyin:"抖音",tiktok:"TikTok",youtube:"YouTube"};
const metricLabels:Record<string,string>={play_count:"播放",digg_count:"点赞",like_count:"点赞",comment_count:"评论",share_count:"分享",collect_count:"收藏",admire_count:"赞赏",recommend_count:"推荐",view_count:"观看"};
const number=new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:1});
function duration(seconds:number|null){if(seconds===null)return "—";const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`}

function TranscriptPanel({workId}:{workId:string}){
 const [state,setState]=useState<TranscriptState|null>(null),[error,setError]=useState(""),[starting,setStarting]=useState(false);
 useEffect(()=>{let active=true,timer:ReturnType<typeof setTimeout>;const load=()=>fetch(`/api/works/${encodeURIComponent(workId)}/transcript`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"读取失败");if(active){setState(d);setError("");if(d.transcript?.status==="PENDING"||d.transcript?.status==="PROCESSING")timer=setTimeout(load,3000)}}).catch(e=>active&&setError(e.message));load();return()=>{active=false;clearTimeout(timer)}},[workId]);
 async function start(){setStarting(true);setError("");try{const r=await fetch(`/api/works/${encodeURIComponent(workId)}/transcript`,{method:"POST"}),d=await r.json();if(!r.ok)throw new Error(d.message||"无法开始转写");setState({...state!,availability:"PENDING",action:null,transcript:d.transcript});window.location.reload()}catch(e){setError(e instanceof Error?e.message:"无法开始转写")}finally{setStarting(false)}}
 if(error)return <section className="panel transcript-state"><FileText size={28}/><h2>无法读取逐字稿状态</h2><p>{error}</p></section>;
 if(!state)return <div className="detail-loading"><LoaderCircle className="spin"/>正在检查逐字稿能力…</div>;
 if(state.transcript?.status==="COMPLETED")return <section className="panel transcript-ready"><div className="section-heading"><div><h2>原文逐字稿</h2><p>{state.transcript.language||"语言未标记"} · {state.transcript.provider||"来源未知"}</p></div><Link className="text-link" href={`/works/${workId}?tab=analysis`}>进入内容分析<ArrowUpRight size={15}/></Link></div><div className="transcript-body">{state.transcript.segments?.length?state.transcript.segments.map((segment,index)=><div className="transcript-segment" key={index}><time>{duration(Math.round(segment.start))}</time><p>{segment.text}</p></div>):<p>{state.transcript.text}</p>}</div></section>;
 if(state.transcript?.status==="COMPLETED")return <section className="panel transcript-ready"><div className="section-heading"><div><h2>原文逐字稿</h2><p>{state.transcript.language||"语言未标记"} · {state.transcript.provider||"来源未知"}</p></div></div><div className="transcript-body">{state.transcript.segments?.length?state.transcript.segments.map((segment,index)=><div className="transcript-segment" key={index}><time>{duration(Math.round(segment.start))}</time><p>{segment.text}</p></div>):<p>{state.transcript.text}</p>}</div></section>;
 const youtube=state.availability==="PLATFORM_CAPTIONS",running=state.transcript?.status==="PENDING"||state.transcript?.status==="PROCESSING";
 return <section className="panel transcript-state"><span className="transcript-icon"><FileText size={28}/></span><p className="eyebrow">SOURCE TRANSCRIPT</p><h2>{running?"正在本机生成逐字稿":youtube?"可以检查平台已有字幕":"这条作品需要 ASR 转写"}</h2><p>{running?"正在获取媒体并使用 RTX 显卡转写，页面会自动刷新状态。":state.transcript?.error_summary||state.message}</p><div className="transcript-route"><span className={youtube?"active":""}>平台字幕</span><i>→</i><span className={!youtube?"active":""}>音频 + ASR</span><i>→</i><span>原文逐字稿</span></div>{state.action==="TRANSCRIBE"||state.transcript?.status==="FAILED"?<button className="source-button transcript-start" disabled={starting} onClick={start}>{starting?<LoaderCircle className="spin" size={15}/>:null}{state.transcript?.status==="FAILED"?"重新转写":"开始本地转写"}</button>:null}<div className="quiet-note"><ShieldCheck size={16}/>{youtube?"尚未发起字幕检查，因此没有产生本步骤费用。":"转写在本机运行，不产生 ASR API 费用；开始时会调用一次 TikHub 获取媒体地址。"}</div></section>;
}

type AnalysisState={availability:"READY"|"PENDING"|"PROCESSING"|"FAILED"|"NEEDS_TRANSCRIPT"|"LLM_REQUIRED"|"READY_TO_ANALYZE";message?:string;analysis:null|{status:string;analysis_language:string;result:Record<string,unknown>|null;error_summary:string|null}};

function AnalysisPanel({workId}:{workId:string}){
 const [state,setState]=useState<AnalysisState|null>(null),[error,setError]=useState(""),[starting,setStarting]=useState(false);
 useEffect(()=>{let active=true,timer:ReturnType<typeof setTimeout>;const load=()=>fetch(`/api/works/${encodeURIComponent(workId)}/analysis`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"读取失败");if(active){setState(d);setError("");if(d.availability==="PENDING"||d.availability==="PROCESSING")timer=setTimeout(load,3000)}}).catch(e=>active&&setError(e.message));load();return()=>{active=false;clearTimeout(timer)}},[workId]);
 async function start(){setStarting(true);try{const r=await fetch(`/api/works/${encodeURIComponent(workId)}/analysis`,{method:"POST"}),d=await r.json();if(!r.ok)throw new Error(d.message||"无法开始分析");setState({...state!,availability:"PENDING"})}catch(e){setError(e instanceof Error?e.message:"无法开始分析")}finally{setStarting(false)}}
 if(error)return <section className="panel transcript-state"><BarChart3 size={28}/><h2>无法读取分析状态</h2><p>{error}</p></section>;
 if(!state)return <div className="detail-loading"><LoaderCircle className="spin"/>正在检查分析状态…</div>;
 if(state.availability==="READY"&&state.analysis?.result){const result=state.analysis.result;const list=(key:string)=>(Array.isArray(result[key])?result[key] as string[]:[]);const evidence=(Array.isArray(result.evidence)?result.evidence:[]) as Array<{claim?:string;quote?:string}>;return <section className="analysis-report"><header className="analysis-report-head"><div><p className="eyebrow">AI CONTENT ANALYSIS</p><h2>内容拆解报告</h2><p>{state.analysis.analysis_language} · 基于原文逐字稿</p></div><div className="score-badge"><strong>{result.content_score as number ?? "—"}</strong><span>内容评分</span></div></header><section className="panel analysis-section"><h3>内容摘要</h3><p>{result.summary as string}</p></section><div className="analysis-grid"><section className="panel analysis-section"><h3>开场 Hook</h3><p>{result.hook as string}</p></section><section className="panel analysis-section"><h3>关键要点</h3><ul>{list("key_points").map((x,i)=><li key={i}>{x}</li>)}</ul></section></div><section className="panel analysis-section"><h3>内容结构</h3><ol>{list("structure").map((x,i)=><li key={i}>{x}</li>)}</ol></section><section className="panel analysis-section"><h3>评分理由</h3><ul>{list("score_reasons").map((x,i)=><li key={i}>{x}</li>)}</ul></section><section className="panel analysis-section"><h3>逐字稿证据</h3><div className="evidence-list">{evidence.map((x,i)=><blockquote key={i}><p>{x.claim}</p><cite>“{x.quote}”</cite></blockquote>)}</div></section></section>}
 const needsTranscript=state.availability==="NEEDS_TRANSCRIPT",ready=state.availability==="READY_TO_ANALYZE"||state.availability==="FAILED",running=state.availability==="PENDING"||state.availability==="PROCESSING";
 return <section className="panel transcript-state"><span className="transcript-icon"><BarChart3 size={28}/></span><p className="eyebrow">CONTENT ANALYSIS</p><h2>{needsTranscript?"先完成逐字稿":running?"正在生成内容拆解":ready?"准备分析这条作品":"分析模型尚未配置"}</h2><p>{state.analysis?.error_summary||state.message}</p>{running&&<div className="analysis-progress" aria-label="内容分析进度"><div className="analysis-step done"><b>1</b><span>读取逐字稿</span></div><i/><div className={state.availability==="PROCESSING"?"analysis-step active":"analysis-step"}><b>2</b><span>模型拆解</span></div><i/><div className="analysis-step"><b>3</b><span>保存结果</span></div></div>}{ready&&<button className="source-button transcript-start" disabled={starting} onClick={start}>{starting?<LoaderCircle className="spin" size={15}/>:null}{state.availability==="FAILED"?"重新分析":"开始内容分析"}</button>}<div className="quiet-note"><ShieldCheck size={16}/>{needsTranscript?"分析将基于已保存的原文逐字稿，并保留证据引用。":running?"正在调用已配置的模型，页面会自动刷新状态。":"分析结果将保存为结构化数据，并保留逐字稿证据引用。"}</div></section>;
}

function LegacyWorkDetail({workId}:{workId:string}){
 const search=useSearchParams(),tab=search.get("tab")==="transcript"?"transcript":search.get("tab")==="analysis"?"analysis":"overview";
 const [item,setItem]=useState<Detail|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;fetch(`/api/works/${encodeURIComponent(workId)}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"读取失败");if(active)setItem(d)}).catch(e=>active&&setError(e.message));return()=>{active=false}},[workId]);
 if(error)return <><Link className="back-link" href="/works"><ArrowLeft size={15}/>返回作品库</Link><section className="panel detail-error"><h1>无法打开作品</h1><p>{error}</p></section></>;
 if(!item)return <div className="detail-loading"><LoaderCircle className="spin"/>正在读取作品详情…</div>;
 const meta=item.metadata,metrics=Object.entries(meta?.metrics||{}).filter(([key,value])=>metricLabels[key]&&value!==null);
 if(tab==="analysis")return <><Link className="back-link" href="/works"><ArrowLeft size={15}/>返回作品库</Link><nav className="detail-tabs" aria-label="作品详情"><Link href={`/works/${item.id}`}>概览</Link><Link href={`/works/${item.id}?tab=transcript`}>逐字稿</Link><Link aria-current="page" href={`/works/${item.id}?tab=analysis`}>分析</Link></nav><AnalysisPanel workId={item.id}/></>;
 return <><Link className="back-link" href="/works"><ArrowLeft size={15}/>返回作品库</Link><nav className="detail-tabs" aria-label="作品详情"><Link aria-current={tab==="overview"?"page":undefined} href={`/works/${item.id}`}>概览</Link><Link aria-current={tab==="transcript"?"page":undefined} href={`/works/${item.id}?tab=transcript`}>逐字稿</Link></nav>{tab==="transcript"?<TranscriptPanel workId={item.id}/>:<><div className="detail-layout"><section className="panel work-detail-main">{meta?.cover_url?<img className="work-cover" src={`/api/works/${encodeURIComponent(item.id)}/cover`} alt="作品封面"/>:<div className="work-cover placeholder">暂无封面</div>}<div className="work-detail-copy"><div className="detail-badges"><span>{platforms[item.platform]}</span><span>{item.status==="READY"?"元数据已就绪":"等待采集"}</span></div><h1>{item.title||`作品 ${item.external_id}`}</h1><p className="work-id">作品 ID · {item.external_id}</p><div className="work-facts"><span><UserRound size={16}/>{meta?.author_name||"作者未知"}</span><span><Clock3 size={16}/>{duration(meta?.duration_seconds??null)}</span><span><CalendarDays size={16}/>{meta?.published_at?new Date(meta.published_at).toLocaleDateString("zh-CN"):"发布时间未知"}</span></div><a className="source-button" href={item.source_url} target="_blank" rel="noreferrer">打开平台原作品<ArrowUpRight size={15}/></a></div></section><aside className="panel detail-side"><div className="section-heading"><div><h2><BarChart3 size={17}/>互动指标</h2><p>采集时的平台公开数据</p></div></div>{metrics.length?<dl className="metric-grid">{metrics.map(([key,value])=><div key={key}><dt>{metricLabels[key]}</dt><dd>{typeof value==="number"?number.format(value):value}</dd></div>)}</dl>:<p className="no-metrics">平台未返回可用指标。</p>}<div className="provider-proof"><ShieldCheck size={16}/><div><strong>来源可追溯</strong><p>{meta?`由 ${meta.provider} 获取 · ${new Date(meta.fetched_at).toLocaleString("zh-CN")}`:"尚未采集元数据"}</p></div></div></aside></div><section className="panel detail-boundary"><h2>当前处理边界</h2><p>本页只展示平台返回的基础元数据。尚未下载媒体、生成逐字稿、执行内容分析或产生 AI 评分。</p>{item.latest_task?.error_summary&&<p className="task-error">{item.latest_task.error_summary}</p>}</section></>}</>;
}

export function WorkDetail({workId}:{workId:string}){
 const search=useSearchParams(),requested=search.get("tab"),tab=requested==="transcript"||requested==="analysis"?requested:"overview";
 const [item,setItem]=useState<Detail|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;fetch(`/api/works/${encodeURIComponent(workId)}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"读取失败");if(active)setItem(d)}).catch(e=>active&&setError(e instanceof Error?e.message:"读取失败"));return()=>{active=false}},[workId]);
 if(error)return <><Link className="back-link" href="/works"><ArrowLeft size={15}/>返回作品库</Link><section className="panel detail-error"><h1>无法打开作品</h1><p>{error}</p></section></>;
 if(!item)return <div className="detail-loading"><LoaderCircle className="spin"/>正在读取作品详情…</div>;
 const meta=item.metadata,metrics=Object.entries(meta?.metrics||{}).filter(([key,value])=>metricLabels[key]&&value!==null);
 return <><Link className="back-link" href="/works"><ArrowLeft size={15}/>返回作品库</Link><nav className="detail-tabs" aria-label="作品详情"><Link aria-current={tab==="overview"?"page":undefined} href={`/works/${item.id}`}>概览</Link><Link aria-current={tab==="transcript"?"page":undefined} href={`/works/${item.id}?tab=transcript`}>逐字稿</Link><Link aria-current={tab==="analysis"?"page":undefined} href={`/works/${item.id}?tab=analysis`}>分析</Link></nav>{tab==="transcript"?<TranscriptPanel workId={item.id}/>:tab==="analysis"?<AnalysisPanel workId={item.id}/>:<div className="detail-layout"><section className="panel work-detail-main">{meta?.cover_url?<img className="work-cover" src={`/api/works/${encodeURIComponent(item.id)}/cover`} alt="作品封面"/>:<div className="work-cover placeholder">暂无封面</div>}<div className="work-detail-copy"><div className="detail-badges"><span>{platforms[item.platform]}</span><span>{item.status==="READY"?"元数据已就绪":"等待采集"}</span></div><h1>{item.title||`作品 ${item.external_id}`}</h1><p className="work-id">作品 ID · {item.external_id}</p><div className="work-facts"><span><UserRound size={16}/>{meta?.author_name||"作者未知"}</span><span><Clock3 size={16}/>{duration(meta?.duration_seconds??null)}</span><span><CalendarDays size={16}/>{meta?.published_at?new Date(meta.published_at).toLocaleDateString("zh-CN"):"发布时间未知"}</span></div><a className="source-button" href={item.source_url} target="_blank" rel="noreferrer">打开平台原作品<ArrowUpRight size={15}/></a></div></section><aside className="panel detail-side"><div className="section-heading"><div><h2><BarChart3 size={17}/>互动指标</h2><p>采集时的平台公开数据</p></div></div>{metrics.length?<dl className="metric-grid">{metrics.map(([key,value])=><div key={key}><dt>{metricLabels[key]}</dt><dd>{typeof value==="number"?number.format(value):value}</dd></div>)}</dl>:<p className="no-metrics">平台未返回可用指标。</p>}</aside></div>}</>;
}
