"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { WorkOrganization, emptyPreferences, type WorkPreferences } from "@/components/work-organization";
type Work={id:string;title:string|null;platform:string;external_id:string;status:string;metadata:{author_name:string|null}|null;preferences:WorkPreferences};
const platforms:Record<string,string>={douyin:'抖音',tiktok:'TikTok',youtube:'YouTube'};
export function WorkLibrary(){
 const [items,setItems]=useState<Work[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[platform,setPlatform]=useState('all'),[scope,setScope]=useState('active'),[tag,setTag]=useState('');
 useEffect(()=>{const controller=new AbortController();async function load(){try{const r=await fetch('/api/works',{cache:'no-store',signal:controller.signal});const data=await r.json();if(!r.ok||!Array.isArray(data))throw new Error(data.message||'读取失败');if(!controller.signal.aborted){setItems(data.map(item=>({...item,preferences:item.preferences||emptyPreferences})));setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'读取失败')}finally{if(!controller.signal.aborted)setLoading(false)}}void load();window.addEventListener('creator-radar:refresh',load);return()=>{controller.abort();window.removeEventListener('creator-radar:refresh',load)}},[]);
 const tags=Array.from(new Set(items.flatMap(item=>item.preferences.tags))).sort();
 const shown=items.filter(item=>(platform==='all'||item.platform===platform)&&(scope==='all'||scope==='active'&&!item.preferences.archived||scope==='favorites'&&item.preferences.favorite&&!item.preferences.archived||scope==='archived'&&item.preferences.archived)&&(!tag||item.preferences.tags.includes(tag))&&[item.title,item.external_id,item.metadata?.author_name,...item.preferences.tags].join(' ').toLowerCase().includes(q.trim().toLowerCase()));
 return <section className="panel"><div className="section-heading"><div><h2>作品库 · {shown.length} / {items.length}</h2><p>搜索标题、作者、作品 ID 或标签。归档只隐藏作品，不删除逐字稿、分析或关联草稿。</p></div></div><div className="library-filters"><label>搜索<input aria-label="搜索作品" value={q} onChange={e=>setQ(e.target.value)} placeholder="标题、作者或标签"/></label><label>平台<select aria-label="作品平台" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">全部平台</option>{Object.entries(platforms).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>范围<select aria-label="作品范围" value={scope} onChange={e=>setScope(e.target.value)}><option value="active">未归档</option><option value="favorites">收藏</option><option value="archived">已归档</option><option value="all">全部</option></select></label><label>标签<select aria-label="筛选标签" value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签</option>{tags.map(t=><option key={t} value={t}>{t}</option>)}</select></label></div>{error?<p role="alert">{error}</p>:loading?<p>正在读取作品…</p>:!shown.length?<p className="quiet-note">没有符合条件的作品，请调整筛选或通过右上角添加作品。</p>:<div className="data-list">{shown.map(item=><article className="data-row" key={item.id}><div><Link className="work-title-link" href={`/works/${item.id}`}>{item.title||item.external_id}</Link><span>{item.preferences.tags.join(' · ')||'暂无标签'}</span></div><span>{platforms[item.platform]||item.platform}</span><span>{item.metadata?.author_name||'作者未知'}</span><WorkOrganization workId={item.id} initial={item.preferences} onSaved={preferences=>setItems(current=>current.map(w=>w.id===item.id?{...w,preferences}:w))}/></article>)}</div>}</section>;
}
